<?php

namespace AppBundle\Repository;

/**
 * CandidateReferencesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CandidateReferencesRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $id
     * @param bool $status
     * @return mixed
     */
    public function getReferencesCandidate($id, $status = true){
        $query = $this->createQueryBuilder('cr')
            ->select("cr.id, cr.company, cr.role, cr.specialization, cr.startDate, cr.endDate, cr.isReference, cr.managerFirstName, cr.managerLastName, cr.managerTitle, cr.managerEmail, cr.managerComment ,cr.permission")
            ->where("cr.user = :id")
            ->setParameter('id',$id)
            ->orderBy('cr.id', 'DESC');
        if($status == true){
            $query->andWhere("cr.permission = :true")
                ->setParameter("true", true);
        }


        return $query->getQuery()->getResult();
    }
}
