<?php

namespace AppBundle\Repository;

/**
 * CandidateAchievementsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CandidateQualificationsRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $id
     * @return mixed
     */
    public function getQualificationsCandidate($id){
        return $this->createQueryBuilder('cq')
            ->select('cq.id, cq.type, cq.schoolName, cq.matriculatedYear, cq.completeSubject, cq.tertiaryInstitution, cq.tertiaryInstitutionCustom, cq.levelQ, cq.specificQ, cq.specificQCustom, cq.specialization, cq.specializationCustom, cq.education, cq.startYear, cq.endYear')
            ->where("cq.user = :id")
            ->setParameter('id',$id)
            ->orderBy('cq.id', 'DESC')
            ->getQuery()
            ->getResult();
    }
}
