<?php

namespace AppBundle\Repository;

/**
 * EmailSheduleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailScheduleRepository extends \Doctrine\ORM\EntityRepository
{
}
