<?php

namespace AppBundle\Repository;

/**
 * LoggingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoggingRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param array $params
     * @return mixed
     */
    public function getAllLogging($params=array()){
        $query = $this->createQueryBuilder('l')
            ->select('l')
            ->orderBy('l.created','DESC');

        if(isset($params['adminID']) && !empty($params['adminID']) && intval($params['adminID'])>0){
            $query->andWhere("(l.user = :adminID)")
                ->setParameter('adminID', intval($params['adminID']));
        }

        if(isset($params['type']) && !empty($params['type']) && intval($params['type'])>0){
            $query->andWhere("(l.type = :type)")
                ->setParameter('type', intval($params['type']));
        }

        if(isset($params['search']) && !empty($params['search'])){
            $query->andWhere("(l.title LIKE :search)")
                ->setParameter('search', "%".$params['search']."%");
        }

        if(isset($params['dateStart']) && !empty($params['dateStart'])){
            $startDate = new \DateTime($params['dateStart']);
            $query->andWhere("DATE_FORMAT(l.created, '%Y-%m-%d') >= :dateStart")
                ->setParameter('dateStart', $startDate->format('Y-m-d'));
        }
        if(isset($params['dateEnd']) && !empty($params['dateEnd'])){
            $endDate = new \DateTime($params['dateEnd']);
            $query->andWhere("DATE_FORMAT(l.created, '%Y-%m-%d') <= :dateEnd")
                ->setParameter('dateEnd', $endDate->format('Y-m-d'));
        }

        return $query->getQuery()->getResult();
    }
}
