<?php

namespace AppBundle\Repository;

/**
 * NotificationAdminRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationAdminRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $id
     * @return mixed
     */
    public function getNotify($id){
        $result = $this->createQueryBuilder('na')
            ->select('na.notifyEmail, na.candidateSign, na.candidateFile, na.candidateRequestVideo, na.candidateDeactivate, na.clientSign, na.interviewSetUp, na.jobNew, na.jobChange')
            ->where("na.user = :id")
            ->setParameter('id',$id)
            ->getQuery()
            ->getResult();

        return (!empty($result) && isset($result[0])) ? $result[0] : null;
    }
}
