<?php

namespace AppBundle\Repository;

/**
 * NotificationCandidateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationCandidateRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $id
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getNotify($id){
        return $this->createQueryBuilder('nc')
            ->select('nc.notifyEmail,nc.notifySMS,nc.interviewRequestStatus,nc.interviewRequest,nc.applicationDeclineStatus,nc.applicationDecline,nc.newJobLoadedStatus,nc.newJobLoaded,nc.jobEndingSoonStatus,nc.jobEndingSoon,nc.documentApproveStatus,nc.reminderProfileStatus,nc.reminderProfile')
            ->where("nc.user = :id")
            ->setParameter('id',$id)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
