<?php

namespace AppBundle\Repository;

/**
 * OpportunitiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OpportunitiesRepository extends \Doctrine\ORM\EntityRepository
{
    public function getOpportunitiesWithStatus($id, $status, $params=array()){
        $query = $this->createQueryBuilder('o')
            ->from('AppBundle:CompanyDetails', 'cd')
            ->select('o')
            ->where('o.client = cd.user')
            ->andWhere("o.candidate = :id")
            ->setParameter('id', $id)
            ->andWhere("o.status = :status")
            ->setParameter("status", $status);

        if(isset($params['limit']) && !empty($params['limit'])){
            $query->setMaxResults($params['limit']);
        }

        $query->orderBy('o.created','DESC');

        return $query->getQuery()->getResult();
    }

    /**
     * @param $id
     * @param $status
     * @param array $params
     * @return mixed
     */
    public function getOpportunityForCandidateWithStatus($id, $status, $params = array()){
        $query = $this->createQueryBuilder('o')
            ->select('o')
            ->where('o.candidate = :id')
            ->setParameter('id', $id)
            ->andWhere('o.status = :status')
            ->setParameter('status', $status)
            ->orderBy('o.created', 'DESC');

        if(isset($params['startDate']) && !empty($params['startDate']) && $params['startDate'] != 'null'){
            $date = ($params['startDate'] instanceof \DateTime) ? $params['startDate'] : new \DateTime($params['startDate']);
            if($date instanceof \DateTime){
                $query->andWhere("DATE_FORMAT(o.created, '%Y-%m-%d') >= :startDate")
                    ->setParameter('startDate', $date->format('Y-m-d'));
            }
        }

        if(isset($params['endDate']) && !empty($params['endDate']) && $params['endDate'] != 'null'){
            $date = ($params['endDate'] instanceof \DateTime) ? $params['endDate'] : new \DateTime($params['endDate']);
            if($date instanceof \DateTime){
                $query->andWhere("DATE_FORMAT(o.created, '%Y-%m-%d') <= :endDate")
                    ->setParameter('endDate', $date->format('Y-m-d'));
            }
        }

        return $query->getQuery()->getResult();
    }
}
