<?php

namespace AppBundle\Repository;

/**
 * ViewUniqueProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ViewUniqueProfileRepository extends \Doctrine\ORM\EntityRepository
{
}
