security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_USER: ROLE_USER
        ROLE_CANDIDATE: ROLE_CANDIDATE
        ROLE_CLIENT: ROLE_CLIENT
        ROLE_ADMIN: ROLE_ADMIN
        ROLE_SUPER_ADMIN: [ROLE_SUPER_ADMIN,ROLE_ADMIN]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username       # fos_user.user_provider.username_email does not seem to work (OAuth-spec related ("username + password") ?)

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        oauth_token:                                   # Everyone can access the access token URL.
            pattern:  ^/oauth/v2/token
            security: false

        api_doc:
            pattern:  ^/api/doc
            security: false

        user_register:
            pattern:   ^/api/user(.+)
            methods:   [ GET, POST, PUT ]
            security:  false

        cron:
            pattern:   ^/api/fetch(.+)
            methods:   [ GET, POST, PUT ]
            security:  false

        api:
            pattern:   ^/api
            fos_oauth: true
            stateless: true
            anonymous: false
            access_denied_handler: AppBundle\Security\Error\AccessDeniedHandler

        main:
            anonymous: ~

    access_control:
        - { path: ^/api/doc, roles: [ IS_AUTHENTICATED_ANONYMOUSLY ] }
        - { path: ^/api, roles: [ IS_AUTHENTICATED_FULLY ] }
        - { path: ^/.*, roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
