export const industry = [
  { id: 'Accounting and Auditing', name: 'Accounting and Auditing' },
  { id: 'Advertising and Marketing', name: 'Advertising and Marketing' },
  { id: 'Agriculture', name: 'Agriculture' },
  { id: 'Automotive', name: 'Automotive' },
  { id: 'Building and Construction', name: 'Building and Construction' },
  { id: 'Conservation and Environment', name: 'Conservation and Environment' },
  { id: 'Distribution, Logistics and Transport', name: 'Distribution, Logistics and Transport' },
  { id: 'Education and training', name: 'Education and training' },
  { id: 'Energy,Chemical, Petrochemical, Oil and Gas', name: 'Energy,Chemical, Petrochemical, Oil and Gas' },
  { id: 'Engineering and mining related services', name: 'Engineering and mining related services' },
  { id: 'Entertainment and sport', name: 'Entertainment and sport' },
  { id: 'Financial Services: Banking', name: 'Financial Services: Banking' },
  { id: 'Financial Services: Insurance', name: 'Financial Services: Insurance' },
  { id: 'Financial Services: Other', name: 'Financial Services: Other' },
  { id: 'FMCG', name: 'FMCG' },
  { id: 'Food & Beverage', name: 'Food & Beverage' },
  { id: 'Freight import & export', name: 'Freight import & export' },
  { id: 'Government', name: 'Government' },
  { id: 'HR services', name: 'HR services' },
  { id: 'Investments', name: 'Investments' },
  { id: 'IT', name: 'IT' },
  { id: 'Manufacture', name: 'Manufacture' },
  { id: 'Marketing, Media and Publishing', name: 'Marketing, Media and Publishing' },
  { id: 'Medical, Pharmaceutical, Health & Fitness', name: 'Medical, Pharmaceutical, Health & Fitness' },
  { id: 'Mining', name: 'Mining' },
  { id: 'Non Profit', name: 'Non Profit' },
  { id: 'Professional Services', name: 'Professional Services' },
  { id: 'Property and Real Estate', name: 'Property and Real Estate' },
  { id: 'Telecommunications', name: 'Telecommunications' },
  { id: 'Textiles and clothing', name: 'Textiles and clothing' },
  { id: 'Tourism, Travel, Hospitality & Catering', name: 'Tourism, Travel, Hospitality & Catering' },
  { id: 'Wholesale and Retail', name: 'Wholesale and Retail' },
  { id: 'Other', name: 'Other' }
];
