export const phoneCode = [
  { id: 'Afghanistan', code: '93' },
  { id: 'Albania', code: '355' },
  { id: 'Algeria', code: '213' },
  { id: 'American Samoa', code: '1-684' },
  { id: 'Andorra', code: '376' },
  { id: 'Angola', code: '244' },
  { id: 'Anguilla', code: '1-264' },
  { id: 'Antarctica', code: '672' },
  { id: 'Antigua and Barbuda', code: '1-268' },
  { id: 'Argentina', code: '54' },
  { id: 'Armenia', code: '374' },
  { id: 'Aruba', code: '297' },
  { id: 'Australia', code: '61' },
  { id: 'Austria', code: '43' },
  { id: 'Azerbaijan', code: '994' },
  { id: 'Bahamas', code: '1-242' },
  { id: 'Bahrain', code: '973' },
  { id: 'Bangladesh', code: '880' },
  { id: 'Barbados', code: '1-246' },
  { id: 'Belarus', code: '375' },
  { id: 'Belgium', code: '32' },
  { id: 'Belize', code: '501' },
  { id: 'Benin', code: '229' },
  { id: 'Bermuda', code: '1-441' },
  { id: 'Bhutan', code: '975' },
  { id: 'Bolivia', code: '591' },
  { id: 'Bosnia and Herzegovina', code: '387' },
  { id: 'Botswana', code: '267' },
  { id: 'Brazil', code: '55' },
  { id: 'British Indian Ocean Territory', code: '246' },
  { id: 'British Virgin Islands', code: '1-284' },
  { id: 'Brunei', code: '673' },
  { id: 'Bulgaria', code: '359' },
  { id: 'Burkina Faso', code: '226' },
  { id: 'Myanmar', code: '95' },
  { id: 'Burundi', code: '257' },
  { id: 'Cambodia', code: '855' },
  { id: 'Cameroon', code: '237' },
  { id: 'Canada', code: '1' },
  { id: 'Cape Verde', code: '238' },
  { id: 'Cayman Islands', code: '1-345' },
  { id: 'Central African Republic', code: '236' },
  { id: 'Chad', code: '235' },
  { id: 'Chile', code: '56' },
  { id: 'China', code: '86' },
  { id: 'Christmas Island', code: '61' },
  { id: 'Cocos Islands', code: '61' },
  { id: 'Colombia', code: '57' },
  { id: 'Comoros', code: '269' },
  { id: 'Republic of the Congo', code: '242' },
  { id: 'Democratic Republic of the Congo', code: '243' },
  { id: 'Cook Islands', code: '682' },
  { id: 'Costa Rica', code: '506' },
  { id: 'Croatia', code: '385' },
  { id: 'Cuba', code: '53' },
  { id: 'Curacao', code: '599' },
  { id: 'Cyprus', code: '357' },
  { id: 'Czech Republic', code: '420' },
  { id: 'Denmark', code: '45' },
  { id: 'Djibouti', code: '253' },
  { id: 'Dominica', code: '1-767' },
  { id: 'Dominican Republic', code: '1-809' },
  { id: 'Dominican Republic', code: '1-829' },
  { id: 'Dominican Republic', code: '1-849' },
  { id: 'East Timor', code: '670' },
  { id: 'Ecuador', code: '593' },
  { id: 'Egypt', code: '20' },
  { id: 'El Salvador', code: '503' },
  { id: 'Equatorial Guinea', code: '240' },
  { id: 'Eritrea', code: '291' },
  { id: 'Estonia', code: '372' },
  { id: 'Ethiopia', code: '251' },
  { id: 'Falkland Islands', code: '500' },
  { id: 'Faroe Islands', code: '298' },
  { id: 'Fiji', code: '679' },
  { id: 'Finland', code: '358' },
  { id: 'France', code: '33' },
  { id: 'French Polynesia', code: '689' },
  { id: 'Gabon', code: '241' },
  { id: 'Gambia', code: '220' },
  { id: 'Georgia', code: '995' },
  { id: 'Germany', code: '49' },
  { id: 'Ghana', code: '233' },
  { id: 'Gibraltar', code: '350' },
  { id: 'Greece', code: '30' },
  { id: 'Greenland', code: '299' },
  { id: 'Grenada', code: '1-473' },
  { id: 'Guam', code: '1-671' },
  { id: 'Guatemala', code: '502' },
  { id: 'Guernsey', code: '44-1481' },
  { id: 'Guinea', code: '224' },
  { id: 'Guinea-Bissau', code: '245' },
  { id: 'Guyana', code: '592' },
  { id: 'Haiti', code: '509' },
  { id: 'Honduras', code: '504' },
  { id: 'Hong Kong', code: '852' },
  { id: 'Hungary', code: '36' },
  { id: 'Iceland', code: '354' },
  { id: 'India', code: '91' },
  { id: 'Indonesia', code: '62' },
  { id: 'Iran', code: '98' },
  { id: 'Iraq', code: '964' },
  { id: 'Ireland', code: '353' },
  { id: 'Isle of Man', code: '44-1624' },
  { id: 'Israel', code: '972' },
  { id: 'Italy', code: '39' },
  { id: 'Ivory Coast', code: '225' },
  { id: 'Jamaica', code: '1-876' },
  { id: 'Japan', code: '81' },
  { id: 'Jersey', code: '44-1534' },
  { id: 'Jordan', code: '962' },
  { id: 'Kazakhstan', code: '7' },
  { id: 'Kenya', code: '254' },
  { id: 'Kiribati', code: '686' },
  { id: 'Kosovo', code: '383' },
  { id: 'Kuwait', code: '965' },
  { id: 'Kyrgyzstan', code: '996' },
  { id: 'Laos', code: '856' },
  { id: 'Latvia', code: '371' },
  { id: 'Lebanon', code: '961' },
  { id: 'Lesotho', code: '266' },
  { id: 'Liberia', code: '231' },
  { id: 'Libya', code: '218' },
  { id: 'Liechtenstein', code: '423' },
  { id: 'Lithuania', code: '370' },
  { id: 'Luxembourg', code: '352' },
  { id: 'Macau', code: '853' },
  { id: 'Macedonia', code: '389' },
  { id: 'Madagascar', code: '261' },
  { id: 'Malawi', code: '265' },
  { id: 'Malaysia', code: '60' },
  { id: 'Maldives', code: '960' },
  { id: 'Mali', code: '223' },
  { id: 'Malta', code: '356' },
  { id: 'Marshall Islands', code: '692' },
  { id: 'Mauritania', code: '222' },
  { id: 'Mauritius', code: '230' },
  { id: 'Mayotte', code:	'262' },
  { id: 'Mexico', code:	'52' },
  { id: 'Micronesia', code:	'691' },
  { id: 'Moldova', code: '373' },
  { id: 'Monaco', code:	'377' },
  { id: 'Mongolia', code:	'976' },
  { id: 'Montenegro', code:	'382' },
  { id: 'Montserrat', code:	'1-664' },
  { id: 'Morocco', code: '212' },
  { id: 'Mozambique', code:	'258' },
  { id: 'Namibia', code: '264' },
  { id: 'Nauru', code: '674' },
  { id: 'Nepal', code: '977' },
  { id: 'Netherlands', code: '31' },
  { id: 'Netherlands Antilles', code: '599' },
  { id: 'New Caledonia', code: '687' },
  { id: 'New Zealand', code: '64' },
  { id: 'Nicaragua', code: '505' },
  { id: 'Niger', code: '227' },
  { id: 'Nigeria', code: '234' },
  { id: 'Niue', code: '683' },
  { id: 'Northern Mariana Islands', code: '1-670' },
  { id: 'North Korea', code: '850' },
  { id: 'Norway', code: '47' },
  { id: 'Oman', code: '968' },
  { id: 'Pakistan', code: '92' },
  { id: 'Palau', code: '680' },
  { id: 'Palestine', code: '970' },
  { id: 'Panama', code: '507' },
  { id: 'Papua New Guinea', code: '675' },
  { id: 'Paraguay', code: '595' },
  { id: 'Peru', code: '51' },
  { id: 'Philippines', code: '63' },
  { id: 'Pitcairn', code: '64' },
  { id: 'Poland', code: '48' },
  { id: 'Portugal', code: '351' },
  { id: 'Puerto Rico', code: '1-939' },
  { id: 'Puerto Rico', code: '1-787' },
  { id: 'Qatar', code: '974' },
  { id: 'Reunion', code: '262' },
  { id: 'Romania', code: '40' },
  { id: 'Russia', code: '7' },
  { id: 'Rwanda', code: '250' },
  { id: 'Saint Barthelemy', code: '590' },
  { id: 'Samoa', code: '685' },
  { id: 'San Marino', code: '378' },
  { id: 'Sao Tome and Principe', code: '239' },
  { id: 'Saudi Arabia', code: '966' },
  { id: 'Senegal', code: '221' },
  { id: 'Serbia', code: '381' },
  { id: 'Seychelles', code: '248' },
  { id: 'Sierra Leone', code: '232' },
  { id: 'Singapore', code: '65' },
  { id: 'Sint Maarten', code: '1-721' },
  { id: 'Slovakia', code: '421' },
  { id: 'Slovenia', code: '386' },
  { id: 'Solomon Islands', code: '677' },
  { id: 'Somalia', code: '252' },
  { id: 'South Africa', code: '27' },
  { id: 'South Korea', code: '82' },
  { id: 'South Sudan', code: '211' },
  { id: 'Spain', code: '34' },
  { id: 'Sri Lanka', code: '94' },
  { id: 'Saint Helena', code: '290' },
  { id: 'Saint Kitts and Nevis', code: '1-869' },
  { id: 'Saint Lucia', code: '1-758' },
  { id: 'Saint Martin', code: '590' },
  { id: 'Saint Pierre and Miquelon', code: '508' },
  { id: 'Saint Vincent and the Grenadines', code: '1-784' },
  { id: 'Sudan', code: '249'},
  { id: 'Suricode', code: '597'},
  { id: 'Svalbard and Jan Mayen', code: '47' },
  { id: 'Swaziland', code: '268'},
  { id: 'Sweden', code: '46'},
  { id: 'Switzerland', code: '41'},
  { id: 'Syria', code: '963'},
  { id: 'Taiwan', code: '886'},
  { id: 'Tajikistan', code: '992'},
  { id: 'Tanzania', code: '255'},
  { id: 'Thailand', code: '66'},
  { id: 'Togo', code: '228'},
  { id: 'Tokelau', code: '690'},
  { id: 'Tonga', code: '676'},
  { id: 'Trinidad and Tobago', code: '1-868'},
  { id: 'Tunisia', code: '216'},
  { id: 'Turkey', code: '90'},
  { id: 'Turkmenistan', code: '993'},
  { id: 'Turks and Caicos Islands', code: '1-649' },
  { id: 'Tuvalu', code: '688'},
  { id: 'United Arab Emirates', code: '971' },
  { id: 'Uganda', code: '256'},
  { id: 'United Kingdom', code: '44' },
  { id: 'Ukraine', code: '380'},
  { id: 'Uruguay', code: '598'},
  { id: 'United States', code: '1' },
  { id: 'Uzbekistan', code: '998'},
  { id: 'Vanuatu', code: '678'},
  { id: 'Vatican', code: '379'},
  { id: 'Venezuela', code: '58'},
  { id: 'Vietnam', code: '84'},
  { id: 'U.S. Virgin Islands', code: '1-340' },
  { id: 'Wallis and Futuna', code: '681' },
  { id: 'Western Sahara', code: '212' },
  { id: 'Yemen', code: '967'},
  { id: 'Zambia', code: '260'},
  { id: 'Zimbabwe', code: '263'}
];
